spring:
  data:
    rest:
      basePath: /api
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

security:
  user:
    password: sa
  basic:
    enabled: false

