spring:
  data:
    rest:
      basePath: /api
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    show-sql: false
  jackson:
    deserialization:
      fail_on_unknown_properties: false
      accept_single_value_as_array: true
    serialization:
      write_empty_json_arrays: true
      write_single_elem_arrays_unwrapped: false
      indent_output: true
      write_null_map_values: true
    default-property-inclusion: always
  mail:
    port: 465
    protocol: smtps
    test-connection: true

security:
  user:
    password: sa
  basic:
    enabled: false
logging:
  config: classpath:logback.xml