spring:
  data:
    rest:
      basePath: /api
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    show-sql: false
  datasource:
    url: jdbc:h2:mem:LOOBO;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

security:
  user:
    password: sa
  basic:
    enabled: false
