spring:
  data:
    rest:
      basePath: /api
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    show-sql: false

security:
  user:
    password: sa
  basic:
    enabled: false
