spring:
  datasource:
    url: jdbc:postgresql:S2GDB
    username: S2G
    password: S2G
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
